import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ApiInterceptor } from './presentation/interceptors/api.interceptor';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { NotifyComponent } from '@shared/components/notify/notify.component';

import { AUTH_REPOSITORY_TOKEN } from '@application/ports/persistence/auth.repository';
import { OWNER_APPLICATION_REPOSITORY_TOKEN } from '@application/ports/persistence/owner-application.repository';
import { NOTIFICATION_REPOSITORY_TOKEN } from '@application/ports/persistence/notification.repository';
import { WEBSOCKET_SERVICE_TOKEN } from '@application/ports/websocket.service';
import { CURRENT_USER_PROVIDER_TOKEN } from '@application/ports/current-user.provider';
import { SessionStateService } from '@presentation/services/session-state.service';

import { AuthRepositoryImpl } from '@infrastructure/repositories/auth.repository.impl';
import { OwnerApplicationRepositoryImpl } from '@infrastructure/repositories/owner-application.repository.impl';
import { NotificationRepositoryImpl } from '@infrastructure/repositories/notification.repository.impl';
import { StompWebSocketService } from '@infrastructure/websocket/stomp-websocket.service';

import {
  provideLucideIcons,
  LucideMenu,
  LucideSearch,
  LucideX,
  LucideBell,
  LucideUser,
  LucideHistory,
  LucideStore,
  LucideShieldCheck,
  LucideLogOut,
  LucideFileText,
  LucidePhone,
  LucideMapPin,
  LucideAlertTriangle,
  LucideIdCard,
  LucideBuilding2,
  LucideReceipt,
  LucideHome,
  LucideUploadCloud,
  LucideImage,
  LucideCheckCircle,
  LucideCamera,
  LucideSend,
  LucideMail,
  LucideCalendar,
  LucideSettings,
  LucidePalette,
  LucideLanguages,
  LucideShield,
  LucideLock,
  LucideUnlock,
  LucideKey,
  LucideLogIn,
  LucideTrophy,
  LucideTarget,
  LucideSwords,
  LucideAward,
  LucideHourglass,
  LucideRotateCw,
  LucideZap,
  LucideCalendarCheck,
  LucideBrain,
  LucideTrendingUp,
  LucideActivity,
  LucideClock,
  LucideCreditCard,
  LucideArrowRight,
  LucideStar,
  LucideStarHalf,
  LucideArrowLeft,
  LucideDollarSign,
  LucideHelpCircle,
  LucideInfo,
  LucideCalendarX,
  LucideXCircle,
  LucideWallet,
  LucideCoins,
  LucideSun,
  LucideConciergeBell,
  LucideGavel,
  LucideFlaskConical,
  LucideUsers,
  LucideBadgeCheck,
  LucideGlobe,
  LucideVideo,
  LucideFlame,
  LucideBellOff,
  LucideCheck,
  LucidePlus,
  LucideUserRound,
  LucideSliders,
  LucideSlidersHorizontal,
  LucideEye,
  LucideEyeOff,
  LucideSave,
  LucideKeyRound,
  LucideShieldAlert,
  LucideLoader2,
  LucideCheckCircle2,
  LucideTrash2,
  LucideCheckCheck,
  LucideInbox,
  LucideBellRing
} from '@lucide/angular';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    FormsModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    MatProgressSpinnerModule,
    NotifyComponent
  ],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: ApiInterceptor,
      multi: true
    },
    { provide: AUTH_REPOSITORY_TOKEN, useClass: AuthRepositoryImpl },
    { provide: OWNER_APPLICATION_REPOSITORY_TOKEN, useClass: OwnerApplicationRepositoryImpl },
    { provide: NOTIFICATION_REPOSITORY_TOKEN, useClass: NotificationRepositoryImpl },
    { provide: WEBSOCKET_SERVICE_TOKEN, useClass: StompWebSocketService },
    { provide: CURRENT_USER_PROVIDER_TOKEN, useExisting: SessionStateService },
    provideLucideIcons(
      LucideMenu,
      LucideSearch,
      LucideX,
      LucideBell,
      LucideUser,
      LucideHistory,
      LucideStore,
      LucideShieldCheck,
      LucideLogOut,
      LucideFileText,
      LucidePhone,
      LucideMapPin,
      LucideAlertTriangle,
      LucideIdCard,
      LucideBuilding2,
      LucideReceipt,
      LucideHome,
      LucideUploadCloud,
      LucideImage,
      LucideCheckCircle,
      LucideCamera,
      LucideSend,
      LucideMail,
      LucideCalendar,
      LucideSettings,
      LucidePalette,
      LucideLanguages,
      LucideShield,
      LucideLock,
      LucideUnlock,
      LucideKey,
      LucideLogIn,
      LucideTrophy,
      LucideTarget,
      LucideSwords,
      LucideAward,
      LucideHourglass,
      LucideRotateCw,
      LucideZap,
      LucideCalendarCheck,
      LucideBrain,
      LucideTrendingUp,
      LucideActivity,
      LucideClock,
      LucideCreditCard,
      LucideArrowRight,
      LucideStar,
      LucideStarHalf,
      LucideArrowLeft,
      LucideDollarSign,
      LucideHelpCircle,
      LucideInfo,
      LucideCalendarX,
      LucideXCircle,
      LucideWallet,
      LucideCoins,
      LucideSun,
      LucideConciergeBell,
      LucideGavel,
      LucideFlaskConical,
      LucideUsers,
      LucideBadgeCheck,
      LucideGlobe,
      LucideVideo,
      LucideFlame,
      LucideBellOff,
      LucideCheck,
      LucidePlus,
      LucideUserRound,
      LucideSliders,
      LucideSlidersHorizontal,
      LucideEye,
      LucideEyeOff,
      LucideSave,
      LucideKeyRound,
      LucideShieldAlert,
      LucideLoader2,
      LucideCheckCircle2,
      LucideTrash2,
      LucideCheckCheck,
      LucideInbox,
      LucideBellRing
    )
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
